//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.18 at 05:44:47 AM PDT 
//


package com.odisei.provisioning;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtensionInfoListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtensionInfoListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MasterExtensionInfoList" type="{}MasterExtensionInfoListType"/>
 *         &lt;element name="SlaveExtensionInfoList" type="{}SlaveExtensionInfoListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtensionInfoListType", propOrder = {
    "masterExtensionInfoList",
    "slaveExtensionInfoList"
})
public class ExtensionInfoListType {

    @XmlElement(name = "MasterExtensionInfoList", required = true)
    protected MasterExtensionInfoListType masterExtensionInfoList;
    @XmlElement(name = "SlaveExtensionInfoList", required = true)
    protected SlaveExtensionInfoListType slaveExtensionInfoList;

    /**
     * Gets the value of the masterExtensionInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link MasterExtensionInfoListType }
     *     
     */
    public MasterExtensionInfoListType getMasterExtensionInfoList() {
        return masterExtensionInfoList;
    }

    /**
     * Sets the value of the masterExtensionInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MasterExtensionInfoListType }
     *     
     */
    public void setMasterExtensionInfoList(MasterExtensionInfoListType value) {
        this.masterExtensionInfoList = value;
    }

    /**
     * Gets the value of the slaveExtensionInfoList property.
     * 
     * @return
     *     possible object is
     *     {@link SlaveExtensionInfoListType }
     *     
     */
    public SlaveExtensionInfoListType getSlaveExtensionInfoList() {
        return slaveExtensionInfoList;
    }

    /**
     * Sets the value of the slaveExtensionInfoList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SlaveExtensionInfoListType }
     *     
     */
    public void setSlaveExtensionInfoList(SlaveExtensionInfoListType value) {
        this.slaveExtensionInfoList = value;
    }

}
