//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.18 at 05:44:47 AM PDT 
//


package com.odisei.provisioning;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.odisei.provisioning package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SlaveExtensionInfoList_QNAME = new QName("", "SlaveExtensionInfoList");
    private final static QName _MasterExtensionInfo_QNAME = new QName("", "MasterExtensionInfo");
    private final static QName _MasterExtensionInfoList_QNAME = new QName("", "MasterExtensionInfoList");
    private final static QName _SlaveExtensionInfo_QNAME = new QName("", "SlaveExtensionInfo");
    private final static QName _ExtensionInfoList_QNAME = new QName("", "ExtensionInfoList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.odisei.provisioning
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SlaveExtensionInfoType }
     * 
     */
    public SlaveExtensionInfoType createSlaveExtensionInfoType() {
        return new SlaveExtensionInfoType();
    }

    /**
     * Create an instance of {@link ExtensionInfoListType }
     * 
     */
    public ExtensionInfoListType createExtensionInfoListType() {
        return new ExtensionInfoListType();
    }

    /**
     * Create an instance of {@link MasterExtensionInfoListType }
     * 
     */
    public MasterExtensionInfoListType createMasterExtensionInfoListType() {
        return new MasterExtensionInfoListType();
    }

    /**
     * Create an instance of {@link ExtensionInfoType }
     * 
     */
    public ExtensionInfoType createExtensionInfoType() {
        return new ExtensionInfoType();
    }

    /**
     * Create an instance of {@link SlaveExtensionInfoListType }
     * 
     */
    public SlaveExtensionInfoListType createSlaveExtensionInfoListType() {
        return new SlaveExtensionInfoListType();
    }

    /**
     * Create an instance of {@link MasterExtensionInfoType }
     * 
     */
    public MasterExtensionInfoType createMasterExtensionInfoType() {
        return new MasterExtensionInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlaveExtensionInfoListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SlaveExtensionInfoList")
    public JAXBElement<SlaveExtensionInfoListType> createSlaveExtensionInfoList(SlaveExtensionInfoListType value) {
        return new JAXBElement<SlaveExtensionInfoListType>(_SlaveExtensionInfoList_QNAME, SlaveExtensionInfoListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MasterExtensionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MasterExtensionInfo")
    public JAXBElement<MasterExtensionInfoType> createMasterExtensionInfo(MasterExtensionInfoType value) {
        return new JAXBElement<MasterExtensionInfoType>(_MasterExtensionInfo_QNAME, MasterExtensionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MasterExtensionInfoListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MasterExtensionInfoList")
    public JAXBElement<MasterExtensionInfoListType> createMasterExtensionInfoList(MasterExtensionInfoListType value) {
        return new JAXBElement<MasterExtensionInfoListType>(_MasterExtensionInfoList_QNAME, MasterExtensionInfoListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlaveExtensionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SlaveExtensionInfo")
    public JAXBElement<SlaveExtensionInfoType> createSlaveExtensionInfo(SlaveExtensionInfoType value) {
        return new JAXBElement<SlaveExtensionInfoType>(_SlaveExtensionInfo_QNAME, SlaveExtensionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionInfoListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExtensionInfoList")
    public JAXBElement<ExtensionInfoListType> createExtensionInfoList(ExtensionInfoListType value) {
        return new JAXBElement<ExtensionInfoListType>(_ExtensionInfoList_QNAME, ExtensionInfoListType.class, null, value);
    }

}
